// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using example2.Data;

#nullable disable

namespace example2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("example2.Models.Categorie", b =>
                {
                    b.Property<int>("Id_Categorie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Categorie"), 1L, 1);

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Categorie");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("example2.Models.Commande", b =>
                {
                    b.Property<int>("Id_Commande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Commande"), 1L, 1);

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Devis")
                        .HasColumnType("int");

                    b.Property<int>("Id_Partenaire")
                        .HasColumnType("int");

                    b.Property<decimal>("MontantHT")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTTC")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTVA")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroCommande")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Commande");

                    b.HasIndex("Id_Devis")
                        .IsUnique();

                    b.HasIndex("Id_Partenaire");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("example2.Models.CommandeLigne", b =>
                {
                    b.Property<int>("Id_CommandeLigne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_CommandeLigne"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Commande")
                        .HasColumnType("int");

                    b.Property<int>("Id_Produit")
                        .HasColumnType("int");

                    b.Property<decimal>("MontantHT")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTTC")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrixUniversitaire")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantite")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Remise")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TauxTVA")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_CommandeLigne");

                    b.HasIndex("Id_Commande");

                    b.HasIndex("Id_Produit");

                    b.ToTable("CommandeLignes");
                });

            modelBuilder.Entity("example2.Models.Devis", b =>
                {
                    b.Property<int>("Id_Devis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Devis"), 1L, 1);

                    b.Property<string>("AdresseFacturation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdresseLivraison")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateDevis")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateValidite")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Partenaire")
                        .HasColumnType("int");

                    b.Property<decimal>("MontantHT")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTTC")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTVA")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroDevis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Devis");

                    b.HasIndex("Id_Partenaire");

                    b.ToTable("Devis");
                });

            modelBuilder.Entity("example2.Models.DevisLigne", b =>
                {
                    b.Property<int>("Id_DevisLigne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_DevisLigne"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Devis")
                        .HasColumnType("int");

                    b.Property<int>("Id_Produit")
                        .HasColumnType("int");

                    b.Property<decimal>("MontantHT")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTTC")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrixUniversitaire")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantite")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Remise")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TauxTVA")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_DevisLigne");

                    b.HasIndex("Id_Devis");

                    b.HasIndex("Id_Produit");

                    b.ToTable("DevisLignes");
                });

            modelBuilder.Entity("example2.Models.Facture", b =>
                {
                    b.Property<int>("Id_Facture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Facture"), 1L, 1);

                    b.Property<DateTime>("DateEcheance")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFacture")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Commande")
                        .HasColumnType("int");

                    b.Property<int>("Id_Partenaire")
                        .HasColumnType("int");

                    b.Property<decimal>("MontantPaye")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroFacture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Facture");

                    b.HasIndex("Id_Commande")
                        .IsUnique();

                    b.HasIndex("Id_Partenaire");

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("example2.Models.Livraison", b =>
                {
                    b.Property<int>("Id_Livraison")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Livraison"), 1L, 1);

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateEcheance")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePrevue")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Commande")
                        .HasColumnType("int");

                    b.Property<string>("NumeroLivraison")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Livraison");

                    b.HasIndex("Id_Commande");

                    b.ToTable("Livraisons");
                });

            modelBuilder.Entity("example2.Models.LivraisonLigne", b =>
                {
                    b.Property<int>("Id_LivraisonLigne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_LivraisonLigne"), 1L, 1);

                    b.Property<int>("Id_Livraison")
                        .HasColumnType("int");

                    b.Property<int>("Id_Produit")
                        .HasColumnType("int");

                    b.Property<decimal>("QteCommande")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QteFait")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QteReserve")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_LivraisonLigne");

                    b.HasIndex("Id_Livraison");

                    b.HasIndex("Id_Produit");

                    b.ToTable("LivraisonLignes");
                });

            modelBuilder.Entity("example2.Models.Partenaire", b =>
                {
                    b.Property<int>("Id_Partenaire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Partenaire"), 1L, 1);

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entreprise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Partenaire");

                    b.ToTable("Partenaires");
                });

            modelBuilder.Entity("example2.Models.Produit", b =>
                {
                    b.Property<int>("Id_Produit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Produit"), 1L, 1);

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Categorie")
                        .HasColumnType("int");

                    b.Property<decimal>("PrixUniversitaire")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QuantiteStock")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TauxTVA")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Produit");

                    b.HasIndex("Id_Categorie");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("example2.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("example2.Models.Commande", b =>
                {
                    b.HasOne("example2.Models.Devis", "Devis")
                        .WithOne("Commande")
                        .HasForeignKey("example2.Models.Commande", "Id_Devis")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("example2.Models.Partenaire", "Partenaire")
                        .WithMany("Commandes")
                        .HasForeignKey("Id_Partenaire")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Devis");

                    b.Navigation("Partenaire");
                });

            modelBuilder.Entity("example2.Models.CommandeLigne", b =>
                {
                    b.HasOne("example2.Models.Commande", "Commande")
                        .WithMany("Lignes")
                        .HasForeignKey("Id_Commande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("example2.Models.Produit", "Produit")
                        .WithMany("CommandeLignes")
                        .HasForeignKey("Id_Produit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("example2.Models.Devis", b =>
                {
                    b.HasOne("example2.Models.Partenaire", "Partenaire")
                        .WithMany("Devis")
                        .HasForeignKey("Id_Partenaire")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Partenaire");
                });

            modelBuilder.Entity("example2.Models.DevisLigne", b =>
                {
                    b.HasOne("example2.Models.Devis", "Devis")
                        .WithMany("Lignes")
                        .HasForeignKey("Id_Devis")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("example2.Models.Produit", "Produit")
                        .WithMany("DevisLignes")
                        .HasForeignKey("Id_Produit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Devis");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("example2.Models.Facture", b =>
                {
                    b.HasOne("example2.Models.Commande", "Commande")
                        .WithOne("Facture")
                        .HasForeignKey("example2.Models.Facture", "Id_Commande")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("example2.Models.Partenaire", "Partenaire")
                        .WithMany("Factures")
                        .HasForeignKey("Id_Partenaire")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Partenaire");
                });

            modelBuilder.Entity("example2.Models.Livraison", b =>
                {
                    b.HasOne("example2.Models.Commande", "Commande")
                        .WithMany("Livraisons")
                        .HasForeignKey("Id_Commande")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("example2.Models.LivraisonLigne", b =>
                {
                    b.HasOne("example2.Models.Livraison", "Livraison")
                        .WithMany("Lignes")
                        .HasForeignKey("Id_Livraison")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("example2.Models.Produit", "Produit")
                        .WithMany("LivraisonLignes")
                        .HasForeignKey("Id_Produit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Livraison");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("example2.Models.Produit", b =>
                {
                    b.HasOne("example2.Models.Categorie", "Categorie")
                        .WithMany("Produits")
                        .HasForeignKey("Id_Categorie")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("example2.Models.Categorie", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("example2.Models.Commande", b =>
                {
                    b.Navigation("Facture");

                    b.Navigation("Lignes");

                    b.Navigation("Livraisons");
                });

            modelBuilder.Entity("example2.Models.Devis", b =>
                {
                    b.Navigation("Commande");

                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("example2.Models.Livraison", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("example2.Models.Partenaire", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("Devis");

                    b.Navigation("Factures");
                });

            modelBuilder.Entity("example2.Models.Produit", b =>
                {
                    b.Navigation("CommandeLignes");

                    b.Navigation("DevisLignes");

                    b.Navigation("LivraisonLignes");
                });
#pragma warning restore 612, 618
        }
    }
}
